image: node:12.18.0
stages:
    - install
    - build
    - deploy

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - cat $DO_KEY_FL > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - eval `ssh-agent -s` &&  printf "$DO_FL_PW\n" | ssh-add ~/.ssh/id_rsa
    - touch ~/.ssh/config
    - '[[ -f ./dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cat ~/.ssh/config
    - echo "$DO_STAGE_SERV" >> ~/.ssh/known_hosts
    - echo "$DO_LATEST_SERV" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy-stage:
    stage: deploy
    variables:
        username: $DO_GITLAB_USER
        pass: $DO_GITLAB_PASS
    script:
        - ssh -o StrictHostKeyChecking=no brief@$DO_STAGE_SERV "cd /home/brief/brief-devops/data/brief-back && git config --global user.name "Dev Freelanders" && git config --global user.email "dev@freelanders.co" && git pull https://${username}:${pass}@gitlab.com/freelanders/brief/brief-back.git stage --allow-unrelated-histories && docker restart brief_back"
    environment:
        name: brief-back
        url: http://stage.freelanders.co/brief_back/
    only:
        - stage

deploy-latest:
    stage: deploy
    variables:
        username: $DO_GITLAB_USER
        pass: $DO_GITLAB_PASS
    script:
         - ssh -o StrictHostKeyChecking=no brief@$DO_LATEST_SERV "cd /home/brief/brief-devops/data/brief-back && git config --global user.name "Dev Freelanders" && git config --global user.email "dev@freelanders.co" && git pull https://${username}:${pass}@gitlab.com/freelanders/brief/brief-back.git latest --allow-unrelated-histories && docker restart brief_back"
    environment:
        name: back-latest
        url: http://latest.freelanders.co/brief_back/
    only:
        - latest
